### ISSUE TITLE
Show files of stack traces

### ISSUE THREAD

**Issue by brianmhunt** [hannoeru/jest-esbuild#8]
### Description

Stack traces currently print out like this:

```ts
      at Object.StaticTable (js.packages/writing/blocks/<stdin>:1:1)
      at Object.get [as StaticTable] (js.packages/writing/blocks/StaticTable.ts:17:45)
      at Object.<anonymous> (js.packages/writing/blocks/<stdin>:44:3)
      at Object.<anonymous> (js.packages/views/<stdin>:4:40)
      at Object.<anonymous> (js.packages/EntityModel/<stdin>:2:36)
```

... but each of the `<stdin>` references are to a file, and it's impossible to know which one is being referenced.

### Suggested solution

Show the filename instead of `<stdin>` e.g.

```ts
      at Object.StaticTable (js.packages/writing/blocks/index.ts:1:1)
      ...
```

### Additional context

It's not clear whether this is a jest-esbuild issue/responsibility, but I can't find any reference to it elsewhere so I wonder if it's something that can/should/must be solved here.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by orzarchi** [comment]
I've fixed it here: https://github.com/hannoeru/jest-esbuild/pull/9
